### ISSUE TITLE
Error Handling & Propagation

### ISSUE THREAD

**Issue by MPSebastian** [amosproj/amos2023ss01-apache-pulsar-ui#103]
## User story
1. As a user
2. I want to a robust software that correctly handles potential errors
3. So that I know when something goes wrong

## Acceptance criteria
* Include Error Handling in the backend (propagation through endpoints if needed)

## Definition of done (DoD)
* Feature is done when the acceptance criteria are fullfiled
* Feature is done when there are test where it is necessary and they pass
* Feature is done when the linter passes
* Feature is done when it is merged onto our main branch (after the code has been reviewed by at least one other person)
* Feature is done when the code has been documentend or commented properly

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by jnsrnhld** [comment]
All backend errors will now be catched:

1. `PulsarApiErrors` HTTP-Code: 500: Anything related to interacting with Pulsar. Example:
```json
{
  "shortMessage": "Could not fetch list a list of all clusters",
  "message": "Could not fetch list a list of all clusters: java.util.concurrent.CompletionException: org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector$RetryException: Could not complete the operation. Number of retries has been exhausted. Failed reason: Connection refused: localhost/[0:0:0:0:0:0:0:1]:8080",
  "type": "org.apache.pulsar.client.admin.PulsarAdminException"
}
```

2. `BadRequestErrors` HTTP-Code: 400: Anything related to passing bad parameters. Example:
```json
{
  "message": "Topic name invalid.",
  "hint": "Valid topic must have schema: {persistent|non-persistent}://tenant/namespace/topic"
}
```

3. `UnknownError` HTTP-Code: 500: Any other type of error. Example:
```json
{
  "shortMessage": "Unknown error",
  "message": "Unknown error: Index 1 out of bounds for length 0.",
  "type": "java.lang.ArrayIndexOutOfBoundsException"
}
```
