### ISSUE TITLE
Add Schema to Topic Details Endpoint

### ISSUE THREAD

**Issue by phildree** [amosproj/amos2023ss01-apache-pulsar-ui#114]
## User story
1. As a frontend-dev 
3. I want the topic detail endpoint to provide the current schema
4. So that I can show it in the UI

## Acceptance criteria
* [ ] Add schema to topic detail endpoint

## Definition of done (DoD)
* Feature is done when the acceptance criteria are fullfiled
* Feature is done when there are test where it is necessary and they pass
* Feature is done when the linter passes
* Feature is done when it is merged onto our main branch (after the code has been reviewed by at least one other person)
* Feature is done when the code has been documentend or commented properly

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by jnsrnhld** [comment]
`TopicDetail` now looks like this: 
```json
{
  "name": "persistent://neuron-demo/customer/command.create-customer.v1",
  "localName": "command.create-customer.v1",
  "namespace": "customer",
  "tenant": "neuron-demo",
  "ownerBroker": "pulsar://localhost:6650",
  "topicStatsDto": {
    "subscriptions": [
      "tech-rbi-neuron-demo-create-customer"
    ],
    "producers": [
      "tech-rbi-neuron-demo-create-customer"
    ],
    "numberSubscriptions": 1,
    "numberProducers": 1,
    "producedMesages": 1,
    "consumedMessages": 0,
    "averageMessageSize": 0,
    "storageSize": 77103
  },
  "schemaInfos": [
    {
      "name": "command.create-customer.v1",
      "version": 0,
      "type": "AVRO",
      "properties": {},
      "schemaDefinition": "{\n \"type\": \"record\",\n \"name\": \"CreateCustomer\",\n \"fields\": [\n  {\n   \"name\": \"numberOfPartitions\",\n   \"type\": [\n    \"null\",\n    \"int\"\n   ]\n  },\n  {\n   \"name\": \"customerBaseMin\",\n   \"type\": \"int\"\n  },\n  {\n   \"name\": \"customerBaseMax\",\n   \"type\": \"int\"\n  },\n  {\n   \"name\": \"publishIntervalSeconds\",\n   \"type\": \"int\"\n  },\n  {\n   \"name\": \"maxPublishCountPerRun\",\n   \"type\": \"int\"\n  },\n  {\n   \"name\": \"publishRandomizeMin\",\n   \"type\": [\n    \"null\",\n    \"float\"\n   ]\n  },\n  {\n   \"name\": \"publishRandomizeMax\",\n   \"type\": [\n    \"null\",\n    \"float\"\n   ]\n  }\n ]\n}",
      "timestamp": "2023-06-06T07:07:40.032+00:00"
    }
  ],
  "persistent": true
}
```

It will show ALL schema versions for a topic and the list of `schemaInfos` will be sorted by the schema version.
