### ISSUE TITLE
Setup AWS VM to host a persistent Apache Pulsar Instace

### ISSUE THREAD

**Issue by phildree** [amosproj/amos2023ss01-apache-pulsar-ui#142]
## User story
1. As a Team
2. We want to know how fast our application is
3. So that we can find potential issues and address them timely

## Acceptance criteria
* Setup VM running an apache pulsar instance

## Definition of done (DoD)
* Feature is done when the acceptance criteria are fullfiled
* Feature is done when there are test where it is necessary and they pass
* Feature is done when the linter passes
* Feature is done when it is merged onto our main branch (after the code has been reviewed by at least one other person)
* Feature is done when the code has been documentend or commented properly

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by jnsrnhld** [comment]
**Step 1: Launch an EC2 Instance**
- Go to the EC2 service.
- Click on "Launch Instances" to start the instance creation wizard.
- Choose an Amazon Machine Image (AMI) that meets your requirements, such as an Amazon Linux or Ubuntu AMI.
- Select an instance type based on your needs, considering CPU, memory, and storage requirements.
- Configure the instance details, including the number of instances, network settings, and storage options.
- Configure security groups to allow inbound SSH traffic (port 22) for remote access.
- Review the instance details and click on "Launch" to start the VM creation process.
- Choose or create an SSH key pair to securely connect to the instance.

**Step 2: Log into the VM via SSH**
- Once the instance is running, note its public IP address or public DNS name.
- Open a terminal or command prompt on your local machine.
- Use the SSH command to connect to the instance. For example:
```shell
ssh -i /path/to/private/key.pem ec2-user@public-ip-or-dns
```
Replace `/path/to/private/key.pem` with the path to your SSH private key, and `public-ip-or-dns` with the actual IP address or DNS name of your instance.
- If prompted, confirm connecting to the host by typing "yes" or "y".

**Step 3: Pull the GitHub Repository**
- Ensure Git is installed on the VM. If not, install it by running the appropriate command based on your Linux distribution. For example, on Amazon Linux or Ubuntu:
```shell
sudo yum install git    # Amazon Linux
sudo apt-get install git    # Ubuntu
```
- Change to the desired directory where you want to clone the repository.
- Clone the repository using the `git clone` command. For example:
```shell
git clone https://github.com/username/repository.git
```
Replace `https://github.com/username/repository.git` with the actual URL of your GitHub repository.

**Step 4: Install Java, Docker, and Node.js**
- Install Java:
  - For Amazon Linux:
  ```shell
  sudo yum install java-1.8.0-openjdk   # Java 8
  ```
  - For Ubuntu:
  ```shell
  sudo apt-get install openjdk-8-jdk   # Java 8
  ```
- Install Docker:
  - For Amazon Linux:
  ```shell
  sudo amazon-linux-extras install docker
  sudo service docker start
  sudo usermod -a -G docker ec2-user
  ```
  - For Ubuntu:
  ```shell
  sudo apt-get update
  sudo apt-get install docker.io
  sudo systemctl start docker
  sudo systemctl enable docker
  sudo usermod -aG docker ${USER}
  ```
- Install Node.js:
  - For Amazon Linux:
  ```shell
  curl -sL https://rpm.nodesource.com/setup_14.x | sudo bash -
  sudo yum install -y nodejs
  ```
  - For Ubuntu:
  ```shell
  curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
  sudo apt-get install -y nodejs
  ```

Now you have successfully created an AWS VM, logged into the VM via SSH, pulled a GitHub repository, and installed the required software (Java, Docker, and Node.js) from within the repository. You can proceed with further configuration or running the software as per the repository's instructions.

**Comment by jnsrnhld** [comment]
@phildree @MPSebastian 
If you want to have a look: http://13.49.158.228:8082/ 

I may shut the machine down in the meantime.
Be aware that we are still creating topics in the background - it takes hours to create the target amount ~5000...

**Comment by jnsrnhld** [comment]
@phildree @MPSebastian for the demo later on:

http://16.16.92.163:8082/cluster

![Image](https://github.com/amosproj/amos2023ss01-apache-pulsar-ui/assets/85998450/298e0bd5-ec6c-4bdc-8053-74cacb1be963)

I created a topic with an attached schema, see above screenshot.

**Comment by jnsrnhld** [comment]
If you want to see some messages: 
http://16.16.92.163:8081/api/swagger-ui/index.html#/message-controller/getMessages
Click on "Try it out", insert topic "persistent://neuron-demo/customer/command.create-customer.v1" and execute!


![Image](https://github.com/amosproj/amos2023ss01-apache-pulsar-ui/assets/85998450/9126f0f5-e122-4525-91b3-e184e6a52f22)
